### ISSUE TITLE
No webhook route for gitlab

### ISSUE THREAD

**Issue by ypereirareis** [ludofleury/satisfy#102]
Hi and thanks for this project !!

Impossible to call the URL /webhook/gitlab because always returning a 404 not found.

```
./bin/console debug:router
 ------------------- ------------ -------- ------ ---------------------------- 
  Name                Method       Scheme   Host   Path                        
 ------------------- ------------ -------- ------ ---------------------------- 
  index               ANY          ANY      ANY    /                           
  login               ANY          ANY      ANY    /login                      
  repository          GET          ANY      ANY    /admin                      
  repository_         GET          ANY      ANY    /admin/                     
  repository_new      GET|POST     ANY      ANY    /admin/new                  
  repository_upload   GET|POST     ANY      ANY    /admin/upload               
  repository_edit     GET|POST     ANY      ANY    /admin/edit/{repository}    
  repository_delete   GET|DELETE   ANY      ANY    /admin/delete/{repository}  
  configuration       GET|POST     ANY      ANY    /admin/configuration        
  satis_build         GET          ANY      ANY    /admin/satis/build          
  satis_build_run     GET          ANY      ANY    /admin/satis/buildRun       
  webhook_bitbucket   GET|POST     ANY      ANY    /webhook/bitbucket          
  webhook_github      GET|POST     ANY      ANY    /webhook/github             
 ------------------- ------------ -------- ------ ----------------------------

No route listed for gitlab webhook.
THanks
```

**Comment by ramunasd** [comment]
Hi, that is strage @ypereirareis . Please make sure You are using latest `master` branch and no source files was changed. Also, can You report PHP version?

**Comment by ypereirareis** [comment]
Hello! Ok you are right, the route is there on dev-master branch when installing with :

`composer create-project playbloom/satisfy:dev-master`.

But didn't try the hook so far. I'll keep you posted when I can test it.
Is there a 3.2 release planned ?

Thx

**Comment by ypereirareis** [comment]
So it's working for dev-master BUT the request body sent by gitlab is now no more compatible with the code https://docs.gitlab.com/12.0/ee/user/project/integrations/webhooks.html

> Note: Starting from GitLab 8.5: - the repository key is deprecated in favor of the project key - the project.ssh_url key is deprecated in favor of the project.git_ssh_url key - the project.http_url key is deprecated in favor of the project.git_http_url key

I'll work on a PR if I have time.

THX

**Comment by ramunasd** [comment]
Thanks, we could release this fix in 3.2 version.

**Comment by ypereirareis** [comment]
Hi!
Here is the PR #103 
Please tell me when a new version is released ! THX

**Comment by ramunasd** [comment]
Cool, nice work. Thank You.
