### ISSUE TITLE
ramunasd/symfony-container-mocks is not a dev dependency

### ISSUE THREAD

**Issue by shochdoerfer** [ludofleury/satisfy#110]
I tried to install the satisfy dependencies with `composer install --no-dev`. 

When accessing Satisfy afterward, I get an error stating that a trait from the package `ramunasd/symfony-container-mocks` can't be found since the MicroKernel uses that trait. The solution would be to convert ramunasd/symfony-container-mocks to a regular dependency. Can provice a PR if that makes sense for you.

**Comment by ramunasd** [comment]
Absolutely! This is a community based project so please feel free to submit any improvements ;)
