### ISSUE TITLE
Make Satisfy `composer install --no-dev` for production release

### ISSUE THREAD

**Issue by oh4real** [ludofleury/satisfy#115]
In order to build a clean artifact image for production deployment, I built an image with `composer install --no-dev`. Sadly, the image failed to work, because of the test-related TestKernelTrait declared in the MicroKernel.

I tried a quick pass (see https://github.com/ludofleury/satisfy/pull/113), but it failed the build tests - for now obvious reasons.

I might continue to work on bypassing this - maybe a custom TestMicroKernel that extends a prod ready MicroKernel, however, I am not at all well-versed on Symfony framework.

If you can be quicker to refactor TestKernelTrait out of MicroKernel, that would be great.

**Comment by ramunasd** [comment]
What causes Your concerns? Package size? Well, dev dependencies consumes only extra 20Mb. Hardly it's a problem for modern servers, thus they have no impact on runtime.

**Comment by oh4real** [comment]
Standard best practice is to deploy only required packages.  The "require-dev" is for "dev" purposes only: test, compilation (e.g.javascript/css), static analysis and build. 

For example: https://laravel.com/docs/6.x/deployment#autoloader-optimization every framework, every best practices blog says same.

Seems wrong/odd having a "TestKernelTrait" in the production MicroKernel. 

Note: only one test in the suite fails when test trait is removed: https://travis-ci.org/ludofleury/satisfy/jobs/613164402?utm_medium=notification&utm_source=github_status, might be an easy update
