### ISSUE TITLE
./bin/satis keeps asking for credentials

### ISSUE THREAD

**Issue by renepardon** [ludofleury/satisfy#121]
Hello,
i've just installed newest Satisfy version and changed the app/config/parameters.yml to include the Token of my satis user from Gitlab. But as soon as I run `./bin/satis build` the CLI is asking me to provide credentials for this user.
Maybe I'm on a wrong path but if an access token is not working this way, how can I provide it? The tool is asking for credentials for every repository I've added to the satis.json file.

So I would prefer providing the credentials through ENV or even better providing a username and SSH key to access Gitlab. Maybe you can point me to the right direction here.

**Comment by ramunasd** [comment]
You must configure composer auth not satisfy.
Not enough info/how to reproduce.

**Comment by renepardon** [comment]
@ramunasd thank you for the hint. Placing an auth.json with the user credentials of the private repository (Gitlab) and using the command like this works:

`GIT_ASKPASS=echo ./bin/satis build`
