### ISSUE TITLE
composer.lock partial upload

### ISSUE THREAD

**Issue by ThomasNegeli** [ludofleury/satisfy#130]
Currently, if not all of the entries from the composer.lock have a `source` entry, the whole file is ignored.
If you work with private composer repositories this is a problem, because there we have mixed content. Some packages are from the private source, some are from github.com via packagist.org and some are from other repositories.
In this case it would help, if the entries with the missing `source` entries are just ignored.

As far as i can see, the problem comes from the form validation and the schema defined here: https://github.com/ludofleury/satisfy/blob/master/src/Playbloom/Satisfy/Resources/schemas/composer_lock.json#L30

What do you think about changing this behaviour?

**Comment by ThomasNegeli** [comment]
I just removed the line in the file from above.
Now the upload ignores the packages with the missing source identifier.
There is no warning shown, but this solves our problem currently.

**Comment by ramunasd** [comment]
This is community based project and all contributions are welcome. I would like to review PR for this fix.
