### ISSUE TITLE
[question] gitlab repository

### ISSUE THREAD

**Issue by p418** [ludofleury/satisfy#139]
Hi!
First of all, thanks you for your work..

I managed to set up a working satisfy instance but at some point, I can't figure out how to use it.

When trying to add a new "gitlab" repository, what information do I need to provide ?
What the purpose of it and does it works with self-managed gitlab ?

within `parameters.yml`, I can see `gitlab.auto_add_repo` and `gitlab.auto_add_repo_type` parameters and I don't know what I'm suppose to fill in with.

Is there any configuration examples or documentation about satisfy usage ?

Thanks.

**Comment by ramunasd** [comment]
@p418 I would recommend to start reading from satis configuration [1]. You can edit `satis.json` manually and see how it looks in admin page.
All parameters are self-explanatory, You can keep default values if they are unclear to You.

[1] https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md
