### ISSUE TITLE
Gitlab Webhook: Configure to use ssh repository rather than https 

### ISSUE THREAD

**Issue by wilfriedwolf** [ludofleury/satisfy#140]
Hi there,

I'm just about to upgrade my satisfy instance which we are now using perfectly for some years. By then, I wrote a gitlab webhook which still works, but I'd rather use yours, since it can create repositories - great feature.

My problem is, that we are using `git@gitlab.example.com:group/repo.git` for the repositories and not 
`https://gitlab.example.com/group/repo.git`, which gets written in `satis.json` when executing a webhook on a nonexisting repository.

I was playing arround a little, trying to adopt the https way, but I was not successful, since our repos are all private. 
I even created an `auth.json` with the credentials of a user having access to our repo, but on executing

```
$ bin/satis build satis.json public --skip-errors --no-ansi --verbose --repository-url=https://gitlab.example.com/group/repo.git --repository-strict
```
I always get the username promt, so that does not work (or at least I have not found out how to configure it correctly)

My proposal now is to enable configuring the prefered clone url. I found the place where to do it, and I'll do a pull request, if you think this could be a good idea.

Never the less: how are you supposed to handle private gitlab projects?

Best regards,

Willi

**Comment by ramunasd** [comment]
Just change ordering here https://github.com/ludofleury/satisfy/blob/master/src/Playbloom/Satisfy/Webhook/GitlabWebhook.php#L58 , write a test and submit PR. I would love to review it ;)

**Comment by wilfriedwolf** [comment]
The orderings allready changes, and I am willing to write a test, but.. never done it before :( What framework do you use, could you just give me a hint, how to start?

**Comment by ramunasd** [comment]
We use phpunit. There is plenty of tutorials on the web.

**Comment by wilfriedwolf** [comment]
Thank, you I just asked my colleague, and he told me just that :) 

-- 
Wilfried Wolf
Softwareentwicklung

Sandstein Neue Medien GmbH
Goetheallee 6 · Eingang Händelallee · 01309 Dresden
Tel. direkt +49 (0)351 44078-32 · Zentrale +49 (0)351 44078-40 · Fax
+49 (0)351 44078-12
wilfried.wolf@sandstein.de · https://www.sandstein.de/internetagentur 
 
Folgen Sie uns per Facebook - Twitter - Instagram: 
www.facebook.com/Sandstein.de
www.twitter.com/sandstein
www.instagram.com/sandstein_neue_medien



>>> Ramunas Dronga <notifications@github.com> schrieb am Montag, 15.
Juni 2020 um
17:08 in Nachricht
<ludofleury/satisfy/issues/140/644192841@github.com>:
