### ISSUE TITLE
You cannot guess the mime type as the Mime component is not installed. Try running "composer require symfony/mime".

### ISSUE THREAD

**Issue by nickychow** [ludofleury/satisfy#148]
When I tried both 3.2.6 and master branches and experienced this error when it's showing the homepage.  I believe this is probably something to do with the Symfony upgrade. 

I found a similar issue in the Symfony repo: https://github.com/symfony/symfony/issues/37709 . Hope this can help.

Cheers,

**Comment by ramunasd** [comment]
fixed in v3.2.7
