### ISSUE TITLE
[Bug] Tag metadata not well supported

### ISSUE THREAD

**Issue by Gounlaf** [ludofleury/satisfy#149]
Hi,

I have an issue with semver specs: build metadata (https://semver.org/#spec-item-10) are not well supported.

Step to reproduce :
- Create a tag like `v1.0.0+metadata-test-1`
- Make satisfy refresh repos ; you will have the tag correctly
- Create a tag like `v1.0.0+metadata-test-2`
- Make satisfy refresh repos ; you will have `v1.0.0+metadata-test-1` but not `v1.0.0+metadata-test-2`
- Delete tag `v1.0.0+metadata-test-1`
- Make satisfy refresh repos ; you will have `v1.0.0+metadata-test-2`

More disturbing: only the "last created" tag is found;
- Create a tag like `v1.0.0+metadata-test-1` ; OK
- Create a tag like `v1.0.0+metadata-test-2` ; NOT FOUND
- Delete tag `v1.0.0+metadata-test-1`; `v1.0.0+metadata-test-2` Found
- Re-push `v1.0.0+metadata-test-1` ; still not found ;only `v1.0.0+metadata-test-2`

I don't really know if it's `satisfy` that cause the issue or `satis`.
If `satisfy` "do-nothing" about tags and rely only on `satis`, I will open the issue there.

Thanks,

Regards.

**Comment by ramunasd** [comment]
This application does nothing during "refresh", basically it's a `satis build` with all required options.
Please open issue there.
