### ISSUE TITLE
New install does not work

### ISSUE THREAD

**Issue by neoighodaro** [ludofleury/satisfy#151]
On composer install:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires composer/satis dev-master#4ffdaed2aaaf3daf1e4ce1b422d968f8cdc756f9, found composer/satis[dev-main, 1.0.0-alpha1, ..., 1.x-dev, 2.0.x-dev (alias of dev-main)] but it does not match the constraint.```

Is there a fix? I think somehow dev-master is being used

**Comment by ramunasd** [comment]
Latest version requires dev-master#6d4e87b5bdce688d932b7fe696f54b34c70a8ffe
What version do You use? Are You trying to upgrade dependencies?

**Comment by neoighodaro** [comment]
I don't know but `dev-master` should not exist anymore as the repo changed the `master` repo to `main`

**Comment by ramunasd** [comment]
You don't know? huh :) Then please describe steps how to reproduce this exception.

I tried with different branch names and it works. In the end it's just branch name, most important part is commit hash, which can belong to many branches 🤷

**Comment by neoighodaro** [comment]
Alright, I should close the issue. I just know I used the readme at the time which was `dev-master#4ffdaed2aaaf3daf1e4ce1b422d968f8cdc756f9`. 

I actually moved on to a custom way to handle it. Closing, but thanks for the response.
