### ISSUE TITLE
'Service "Playbloom\Satisfy\Service\LockProcessor" not found' error when trying to upload composer.lock file

### ISSUE THREAD

**Issue by dshiryaev-plesk** [ludofleury/satisfy#152]
## STR
1. Open /admin page
2. Press 'Add all repositories from a composer.lock' button
3. Upload a composer.lock file

## Actual result
The page shows the following error:
> Service "Playbloom\Satisfy\Service\LockProcessor" not found: even though it exists in the app's container, the container inside "Playbloom\Satisfy\Controller\RepositoryController" is a smaller service locator that only knows about the "Playbloom\Satisfy\Service\Manager", "Playbloom\Satisfy\Validator\EnvValidator", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "templating" and "twig" services. Try using dependency injection instead.

## Expected result
Satisfy adds all composer repositories from uploaded composer.lock file then shows them at /admin page

## Checked Satisfy versions that has this issue
- 3.2.4
- 3.2.8
- 3.3.0

**Comment by ramunasd** [comment]
fixed
