### ISSUE TITLE
I need a docker to manage upgrades

### ISSUE THREAD

**Issue by a67793581** [ludofleury/satisfy#177]
I need a docker to manage upgrades

**Comment by ramunasd** [comment]
Hello, github issues are intended for registering bugs, unexpected behaviour or feature requests. If You expenrience something like that then explain it in a propriate way please.

**Comment by a67793581** [comment]
Hello, I think I need a Docker image for service deployment and can easily upgrade it.

**Comment by a67793581** [comment]
> 您好，github问题旨在注册错误，意外行为或功能请求。如果你有类似的东西，那么请以适当的方式解释它。

Hello, I think I need a Docker image for service deployment and can easily upgrade it.

**Comment by ramunasd** [comment]
We have dockerfile for development purposes only. Any other images are not provided.

**Comment by LTaooo** [comment]
@a67793581 https://hub.docker.com/repository/docker/ltaooo/satisfy/general
