### ISSUE TITLE
Wrong dependency fp/lightopenid

### ISSUE THREAD

**Issue by ypereirareis** [ludofleury/satisfy#29]
Hello.

fp/lightopenid is DEPRECATED and ABANDONNED.

**Comment by ludofleury** [comment]
Ok, thank you. I will try to find this.

**Comment by anroots** [comment]
Ran into this myself when trying to `composer install`. Please remedy.

**Comment by joska** [comment]
It's advised to migrate to lightopenid/lightopenid. But beware, since July 2015 the Google OpenId 2.0 is officialy discontinued and you have to use Google Sign In.

Satisfy does not have support for this.

**Comment by ludofleury** [comment]
Hello, I'm short on time right now, anyone for a PR ?

**Comment by joska** [comment]
Same here :/ I did not have much expirience with Symphony either. I started a fork with gigablah/silex-oauth authorization library, since it should work even with GitHub, but I doubt I will be able to finish it in upcoming days/weeks.

**Comment by anroots** [comment]
To people who want to use Satisfy without OpenID: a quickfix is to change the dependency name in `composer.json`: [see here](https://github.com/anroots/satisfy/commit/fb6b5dbc7bc37f0a214547402744b30ea75d565b). This will probably break the OpenID login, but not in ways you'd notice if you aren't using it.

My setup is in company LAN and is protected by LDAP Basic Auth provided by Apache.

**Comment by ludofleury** [comment]
Hey guys, I made a really quick & dirty pull request there #30
I didn't tested it. let me know.
