### ISSUE TITLE
Add support for mirrored packages

### ISSUE THREAD

**Issue by ramunasd** [ludofleury/satisfy#41]
One possible solution could be "checkbox" in repository list. Then we could add checked repositories to "require" and "require-dev".

**Comment by ludofleury** [comment]
I'm not familiar with mirrored packages tho

**Comment by ramunasd** [comment]
Well, here is little misunderstanding. "Require" and "require-dev" isn't responsible for dist packages.

To enable dist packages its enough to set `directory` in `archive` property.
