### ISSUE TITLE
Provide docker image

### ISSUE THREAD

**Issue by ludofleury** [ludofleury/satisfy#44]

**Comment by ypereirareis** [comment]
Hi !!

Maybe it could match your needs : [https://github.com/ypereirareis/docker-satis](https://github.com/ypereirareis/docker-satis)

**Comment by ludofleury** [comment]
Hey, very nice ! I have no time for the moment, but I will definitely look an try to see what we can do !

**Comment by ramunasd** [comment]
Already dockerized!
