### ISSUE TITLE
Auto generate the package definition after any update

### ISSUE THREAD

**Issue by ludofleury** [ludofleury/satisfy#45]

**Comment by kevindierkx** [comment]
Is this really required when you use something like a cron that runs the build every minute?

**Comment by ramunasd** [comment]
I have one script for auto rebuild when config is updated or some time passed after last update. I just need to convert it to console command.

**Comment by kevindierkx** [comment]
Still what is the added benefit of some extra logic instead of just using the cron?
The end result would be the same and doesn't require the application to keep track of the last update and making the whole update process less complex.
Besides I don't wan't to access the web interface before I run a `composer update` to make sure I got the latest changes for my packages.

**Comment by ramunasd** [comment]
@kevindierkx everything is simple - if You don't see any benefit then just don't use it :)

**Comment by cumuru** [comment]
@ramunasd Can you provide any code on how you use the console command? How is it triggered?

**Comment by ramunasd** [comment]
@cumuru Sure, what You need is just one command, inside of project dir run this:
```
./bin/console satisfy:rebuild
```

Good luck!

**Comment by cumuru** [comment]
@ramunasd Thanks for your answer. I expected there were a way to trigger a rebuild on configuration change. But the console command you mentioned needs to be fired by a cron again, am I getting it right?
What I‘m trying to achieve is to receive a webhook payload from my repository (gitbucket in my case) on push events and update satis (with `--repository-url https://only.my/repo.git`) once a new repo is added. Unfortunately there‘s no event for the latter, at least I didn‘t find any.

**Comment by ramunasd** [comment]
@cumuru Can You create a new thread for whole webhook/event/trigger issue. We will add it to next milestone ;)

**Comment by cumuru** [comment]
Yep, will do so :-)
