### ISSUE TITLE
Lib NOT WORKING at all !

### ISSUE THREAD

**Issue by ypereirareis** [ludofleury/satisfy#47]
Hello !

I use your lib inside a Docker image https://github.com/ypereirareis/docker-satis

Acutally, a json schema validation has been added on composer/satis (dev-master) a few days ago [https://github.com/composer/satis/blob/9e8ef8e906f204d01ce468dcc123306919488ddc/src/Composer/Satis/Command/BuildCommand.php#L282](https://github.com/composer/satis/blob/9e8ef8e906f204d01ce468dcc123306919488ddc/src/Composer/Satis/Command/BuildCommand.php#L282)

AND

[https://github.com/composer/satis/blob/master/res/satis-schema.json](https://github.com/composer/satis/blob/master/res/satis-schema.json)

The require entry in the JSON file should be an object not an array !

```shell
{
  ...
  require: {}
  ...
}
```

```shell
[Composer\Json\JsonValidationException]                       
  The json config file does not match the expected JSON schema
```

Please fix it, or change the dependency to previous version

THX ! :smile:

**Comment by ludofleury** [comment]
It tooks me some minute to realize what we were talking about, so far after a quick check, I think it comes from the serialization process here https://github.com/ludofleury/satisfy/blob/master/src/Playbloom/Satisfy/Model/Configuration.php#L40

If @ramunasd or you @ypereirareis have a quick fix, I won't be able to update this repo before 2-3 weeks.

**Comment by ramunasd** [comment]
@ypereirareis Can you remove  line `require: {}` and test with latest dev version?

**Comment by ypereirareis** [comment]
Hi @ramunasd !

It's **working** with the latest dev version !

Thx ! :+1:  :smile:

**Comment by ramunasd** [comment]
you're welcome ;) i will create next minor version

**Comment by ludofleury** [comment]
:clap: :clap: thanks guys, amazing.
