### ISSUE TITLE
Stale packages remains when repository is added to same users composer config

### ISSUE THREAD

**Issue by ramunasd** [ludofleury/satisfy#59]
When instance of satisfy is added to composer config, satis gets packages(branches) from previously generated definitions. Even if branch is removed from vcs repository, satis keeps them and shows as available version.

This issue creates stale packages in composer repository and leads to problems when someone tries to install missing branch.

**Comment by ludofleury** [comment]
Sorry, i didnt get you at all

**Comment by ramunasd** [comment]
@ludofleury don't worry, i also didn't got from first try :)

Imagine situation when certain user has satis repository and runs `satis build` periodically. Let's say web url of repository is myrepo.example.com. What happens if this user in it's `~/.composer/config.json` has something like this:
```javascript
{
    "config": {
    },
    "repositories": {
        "example": {
            "type": "composer",
            "url": "http://myrepo.example.com"
        }
    }
}
```

In this case every time user does `satis build`, satis takes all repositories (excluding packagist.org), fetches all packages from there and adds to list of available ones. Even if package was removed from VCS, it exists in last build and remains in next ones.

Well, this bug comes not from satisfy itself, but i'm still noticing here.

**Comment by ludofleury** [comment]
oh wow. It's on satis I think. Did you open a report there ?
