### ISSUE TITLE
Why repository pattern?

### ISSUE THREAD

**Issue by GBeushausen** [ludofleury/satisfy#69]
Why is there a repository pattern and why does it only work with GitHub? This makes the app pretty much useless for people who don't use GitHub.

**Comment by ramunasd** [comment]
@GBeushausen that's because a lot of 3rd party libraries are hosted on github, and don't forget - it's just example :)

**Comment by GBeushausen** [comment]
@ramunasd Yeah. Anyway thanks for the great work.

**Comment by ludofleury** [comment]
Hey, repository pattern on the original implementation was one
architectural way of accessing/manipulating an OO designed “package”. They
are many ways to design this. Is it a so weird/bad choice for the concern?

**Comment by ramunasd** [comment]
Hi @ludofleury , sorry, I don't get what means "OO designed package" and how it is related to repository pattern?
