### ISSUE TITLE
Run satis on repository add or with button on admin panel

### ISSUE THREAD

**Issue by mysiar** [ludofleury/satisfy#70]
It would be great if Satisy could run satis on repository list update or kicked by button.
What do you think ?

**Comment by ramunasd** [comment]
Hi, @mysiar nice idea, will add it for 3.0 release.

**Comment by mysiar** [comment]
Hi @ramunasd do you have any predicted time for releasing **3.0** ?

**Comment by ramunasd** [comment]
No, there is planned time for 3.0. Looks like latest RC is stable and only a few minor things left, except this improvement.
I would appreciate any help ;)
