### ISSUE TITLE
Please use the latest stable version of satis

### ISSUE THREAD

**Issue by bbalet** [ludofleury/satisfy#74]
Hi,

Could you please swicth to the latest stable version of satis which is compatible with PHP7.2. As of today, the generation throw this error:

    [Twig_Error_Runtime]
    An exception has been thrown during the rendering of a template ("count():
    Parameter must be an array or an object that implements Countable") in "pac
    kage.html.twig" at line 91.
    
    [ErrorException]
    count(): Parameter must be an array or an object that implements Countable

And it is solved into the last stable release of satis.

**Comment by ramunasd** [comment]
That's weird, because generation is tested against all latest PHP versions. Do You know how to reproduce this exception?
Anyways, after merge with branch 3.x, latest version of satis is installed. Please reopen if issue still remains.

**Comment by mvorisek** [comment]
Toda I just newly installed satis with command:

    composer create-project composer/satis:dev-master --keep-vcs

following configuration
```
{
  "name": "My Repository",
  "homepage": "http://packages.example.org",
  "repositories": [
    { "type": "vcs", "url": "https://github.com/atk4/data" }
  ],
  "require-all": true
}
```

and run it by:

    php satis/bin/satis build -- satis.json ./data

I confirm the issue, here is the output:
```
Scanning packages
Writing packages.json
Pruning include directories
Writing web view

[Twig_Error_Runtime]
An exception has been thrown during the rendering of a template ("count(): Parameter must be an array or an object      that implements Countable").

[ErrorException]
count(): Parameter must be an array or an object that implements Countable

build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--stats] [--] [<file>] [<output-dir>] [<packages>]...
```

**Comment by mvorisek** [comment]
The issue was it this line:
https://github.com/composer/satis/blob/master/views/package.html.twig#L104
the master is fixed now.

**Comment by ramunasd** [comment]
Hi @mvorisek , latest version 3.0.1 depends on latest composer/satis as well symfony & twig packages.
Please `git pull && composer install` and try again
