### ISSUE TITLE
Add webhook/trigger events

### ISSUE THREAD

**Issue by cumuru** [ludofleury/satisfy#75]
To reduce server load and increase responsiveness I suggest to add two things:
1) a webhook endpoint for triggering satis updates on single repositories (e.g. for Github)
2) an event triggered by satisfy that updates packages.json once a new repository is added (or removed or updated)

In depth:
1) 
* Would be nice to support Github API (https://developer.github.com/webhooks/) and others?
* Should be secured by a secret token (https://developer.github.com/webhooks/securing/). The token should be configurable either in config file or via environment.
* Repository name in (Github) payload is different from satis and needs to be normalized (for SSH)

2)
* An event should fire on every action that modifies the set of repositories. Might trigger a complete rebuild maybe (opinions?)

My goal is to have three ways of updating packages.json:
* A push webhook that rebuilds a single repo
* An event that rebuild a single repo or everything
* A cronjob that runs maybe once a day, just in case any change is missed by the above measures.

See #45.

**Comment by cumuru** [comment]
Some input for implementation:
* satis consumes (on CLI) a param `--repository-url=ssh://git@git.example.com/pathto/repo.git` to update a single repo only
* working Regex to normalize SSH repo uri (Github): 
```preg_replace('/^(\w+@)?([\w\.]+)(:\d+)?:(.*)$/', 'ssh://$1$2$3/$4')```
($1 = user, $2 = host, $3 = port, $4 = repository path)
* composer package dealing with Github API (signature validation and payload normalization): https://packagist.org/packages/swop/github-webhook
* One could iterate over `satis.json`‘s repositories to whitelist incoming push events.

**Comment by ramunasd** [comment]
Bitbucket webhook example:
https://github.com/mtomala/satisfy/commit/a10c1dfa2a7022d1cbc8b74dea28eca789d3b830

A lot of duplicated code, but principe on itself is clear.

**Comment by ramunasd** [comment]
Currently `satis build` with repository filter throws exception.
https://github.com/composer/satis/issues/493

**Comment by ramunasd** [comment]
Implemented & tested against real VCS.
