### ISSUE TITLE
Missing require option

### ISSUE THREAD

**Issue by webmake** [ludofleury/satisfy#79]
Hello,
I checked this project and it is really what we need, but there are some limitations. Now freshly configured satis looks like:
```
{
    "name": "Composer repository",
    "homepage": "http:\/\/localhost",
    "output-dir": "web",
    "output-html": true,
    "repositories": [
        {
            "type": "git",
            "url": "a"
        }
    ],
    "require-all": false,
    "require-dependencies": false,
    "require-dev-dependencies": false,
    "minimum-stability": "dev",
    "providers": false
}
```
But according satis documentation, [there is `require` option](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#setup) to have constraints, so I'm missing this feature to fully replace manual procedure by editing `satis.json` file.

**Comment by ramunasd** [comment]
Hi @webmake , good point, UI form is missing, however this option is not ignored and can be set manully.
