### ISSUE TITLE
NOTICE: PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse Error: syntax error, unexpected ':', expecting ';' or '{'' in /satisfy/src/Playbloom/Satisfy/Service/Manager.php:195"

### ISSUE THREAD

**Issue by ProxiBlue** [ludofleury/satisfy#80]
Seems like there are some errand code after the function is defined.

https://github.com/ludofleury/satisfy/blob/master/src/Playbloom/Satisfy/Service/Manager.php#L195

**Comment by ProxiBlue** [comment]
My bad, this is a PHP7 thing, and I was running 5.6

No problem here, move along please.....

**Comment by ramunasd** [comment]
Yes, looks like. And keep in mind we will set higher minimum required php version in next release.
