### ISSUE TITLE
Gitlab webhook support

### ISSUE THREAD

**Issue by mrcnpdlk** [ludofleury/satisfy#81]
Hi,
Do You have any plan to support gitlab webhook?

**Comment by ramunasd** [comment]
Hi @mrcnpdlk ,
thanks for reaching out. IMHO gitlab webhooks should be supported and is very easy to implement it. Feel free to submit PR.

**Comment by mrcnpdlk** [comment]
Could you tell me how to force satis `rebuild` after `push` event?

**Comment by ramunasd** [comment]
It is enough to dispatch BuildEvent::EVENT_NAME and SatisBuildRunner will run process.
Non zero status code means something went wrong on satis side. Please check whether satis works from command line.

**Comment by mrcnpdlk** [comment]
OK. I found.
`./web` dir doesn't have `write` flag for user/group `www-data`
After chowning and chmoding everything works great. 
Thanks for help.

**Comment by ramunasd** [comment]
So this file permission appears quite often. Would be nice to have a checker/validator for that.
