### ISSUE TITLE
Need full instruction to use your docker-compose build

### ISSUE THREAD

**Issue by 4n70w4** [ludofleury/satisfy#84]
Hi! Tell me all the commands need to execute to make it work!
Access rights and everything else...

`docker-compose up -d`

and next?)

**Comment by ramunasd** [comment]
Hi @4n70w4 , thanks for question.
Default docker-composer.yaml would open 80 port on localhost, so You can type `http://localhost/admin` in Your browser and it will open administration area. Add some packages, wait a little bit and that's it - `http://localhost` should open generated index page.

**Comment by 4n70w4** [comment]
@ramunasd why did you close? I did not confirm the solution to the problem.
So does not work! There are a lot of problems with access rights and other things.
It takes a lot of extra steps to start working without errors.

It would be cool to create detailed step-by-step instructions on how to launch.

**Comment by ramunasd** [comment]
@4n70w4 please feel free to create PR with all required steps and instructions, this is community driven project and any contribution is welcome
