### ISSUE TITLE
Need some help with using webhooks

### ISSUE THREAD

**Issue by VBelozyorov** [ludofleury/satisfy#88]
I'm trying to use gitlab push webhook. 
I've found #82, but failed to make it working for now.

I've specified `<my satisfy host>/webhook/gitlab` as webhook url in gitlab repo's settings.
But my Satisfy instance answers 404 to Gitlab, looks I'm wrong with url? Which it should be?

I've installed Satisfy according to [this instruction](https://github.com/ludofleury/satisfy#installation). Does it install latest version? How can I check this? 
I see only two controllers (Security and Repository) inside `src/Playbloom/Satisfy/Controller` on my server, while there are more [in the repo](https://github.com/ludofleury/satisfy/tree/master/src/Playbloom/Satisfy/Controller). Is my copy outdated?

**Comment by jinnoflife** [comment]
If you pulled the 3.1 release there is actually no gitlab-webhook.
You can try to use the current master-branch for this or wait for the next release.

**Comment by VBelozyorov** [comment]
Ok, I've pulled `master` branch from this repo and executed `composer install -o`. 
Now response to webhook from Satisfy looks fine to me:
```
Response headers:

Server: nginx/1.12.2
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: PHP/7.1.13
Cache-Control: no-cache, private
Date: Tue, 12 Feb 2019 08:22:55 GMT

Response body:

1
```
But "Last updated" time counter on top right corner of Satisfy page hasn't reset after webhook invoked.

I did it using test push hook in gitlab interface. Is some additional configuration needed for satis rebuild?

**Comment by VBelozyorov** [comment]
Well. Seems fixed now. Here quick checklist:

- [ ] Make sure you have Satisfy with GitLab webhook support. For example, try to open <your Satisfy host>/webhook/gitlab in your browser, there shouldn't be 404, (400 is Ok for browser test)
- [ ] Try to execute `bin/satis build` (without arguments) in console at Satisfy root folder. If it requires to `output-dir`, you need to specify it in satis.json. You can submit config from Satisfy's `/admin` webpage.
- [ ] Check write permissions for `/var`, `/web` and `satis.json` for your web-server's process.

**Comment by ramunasd** [comment]
So main problems was unreleased feature and file permissions? @VBelozyorov

**Comment by VBelozyorov** [comment]
Yes. And missing logs from build attempts. I've used satis.json from my previous satis installation, so there wasn't specified `output-dir` and `bin/satis build` hasn't worked without arguments.

**Comment by ramunasd** [comment]
#89 will fix failing build due to missing output-dir
#90 file permission checks
#53 logs
