### ISSUE TITLE
PlaybloomSatisfyBundle::_form.html.twig

### ISSUE THREAD

**Issue by cuijianguo** [ludofleury/satisfy#91]
( ! ) Twig_Error_Loader: Unable to find template "PlaybloomSatisfyBundle::_form.html.twig" (looked into: /data/satis/satisfy/app/Resources/views, /data/satis/satisfy/vendor/symfony/twig-bridge/Resources/views/Form). in /data/satis/satisfy/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 234
--

**Comment by ramunasd** [comment]
Hi @cuijianguo , thanks for reporting. Please post your installed packages from `composer show`.

**Comment by cuijianguo** [comment]
The composer show has many packages, which one should be installed

**Comment by ramunasd** [comment]
Yes, that's right, many packages must present. Please paste here full list.

**Comment by cuijianguo** [comment]
composer/ca-bundle                   1.1.3              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/composer                    1.7.3              Composer helps you declare, manage and install dependencies of PHP projects, ensuring you have the right stack everywhere.
composer/satis                       dev-master 3acf692 Simple Repository Generator
composer/semver                      1.4.2              Semver library that offers utilities, version constraint parsing and validation.
composer/spdx-licenses               1.5.0              SPDX licenses list and validation library.
composer/xdebug-handler              1.3.0              Restarts a process without xdebug.
doctrine/annotations                 v1.6.0             Docblock Annotations Parser
doctrine/instantiator                1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
friendsofphp/php-cs-fixer            v2.13.1            A tool to automatically fix PHP code style
incenteev/composer-parameter-handler v2.1.3             Composer script handling your ignored parameter file
jangregor/phpstan-prophecy           0.2.0              Provides a phpstan/phpstan extension for phpspec/prophecy
jean85/pretty-package-versions       1.2                A wrapper for ocramius/package-versions to get pretty versions strings
jms/metadata                         1.7.0              Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0              A library for easily creating recursive-descent parsers.
jms/serializer                       1.13.0             Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                2.4.2              Allows you to easily serialize, and deserialize data of any complexity
justinrainbow/json-schema            5.2.7              A library to validate a json schema.
mikey179/vfsStream                   v1.6.5             Virtual file system to mock the real file system in unit tests.
myclabs/deep-copy                    1.8.1              Create deep copies (clones) of your objects
nette/bootstrap                      v2.4.6             🅱 Nette Bootstrap: the simple way to configure and bootstrap your Nette application.
nette/di                             v2.4.14            💎 Nette Dependency Injection Container: Flexible, compiled and full-featured DIC with perfectly usable autowiring and support for all new PH...
nette/finder                         v2.4.2             🔍 Nette Finder: find files and directories with an intuitive API.
nette/neon                           v2.4.3             🍸 Nette NEON: encodes and decodes NEON file format.
nette/php-generator                  v3.0.5             🐘 Nette PHP Generator: generates neat PHP code for you. Supports new PHP 7.2 features.
nette/robot-loader                   v3.1.0             🍀 Nette RobotLoader: high performance and comfortable autoloader that will search and autoload classes within your application.
nette/utils                          v2.5.3             🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validation, slug or stron...
nikic/php-parser                     v4.1.0             A PHP parser written in PHP
ninsuo/symfony-collection            2.1.30             A jQuery plugin that manages adding, deleting and moving elements from a Symfony collection
ocramius/package-versions            1.3.0              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
paragonie/random_compat              v9.99.99           PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phar-io/manifest                     1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                      2.0.1              Library for handling version information and constraints
php-cs-fixer/diff                    v1.3.0             sebastian/diff v2 backport support for PHP5.6
phpcollection/phpcollection          0.5.0              General-Purpose Collection Library for PHP
phpdocumentor/reflection-common      1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    4.3.0              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          0.4.0
phpoption/phpoption                  1.5.0              Option Type for PHP
phpspec/prophecy                     1.8.0              Highly opinionated mocking framework for PHP 5.3+
phpstan/phpdoc-parser                0.3                PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan                      0.10.5             PHPStan - PHP Static Analysis Tool
phpstan/phpstan-phpunit              0.10               PHPUnit extensions and rules for PHPStan
phpstan/phpstan-symfony              0.10.2             Symfony Framework extensions and rules for PHPStan
phpunit/php-code-coverage            6.1.4              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            2.0.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1              Simple template engine.
phpunit/php-timer                    2.0.0              Utility class for timing
phpunit/php-token-stream             3.0.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      7.4.4              The PHP Unit Testing framework.
psr/cache                            1.0.1              Common interface for caching libraries
psr/container                        1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1              Common interface for HTTP messages
psr/log                              1.0.2              Common interface for logging libraries
psr/simple-cache                     1.0.1              Common interfaces for simple caching
ramunasd/symfony-container-mocks     0.6                Provides extended Symfony dependency injection container enabling service mocking.
sebastian/code-unit-reverse-lookup   1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                 3.0.2              Provides the functionality to compare PHP values for equality
sebastian/diff                       3.0.1              Diff implementation
sebastian/environment                3.1.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state               2.0.0              Snapshotting of global state
sebastian/object-enumerator          3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations        2.0.1              Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
seld/jsonlint                        1.7.1              JSON Linter
seld/phar-utils                      1.0.1              PHAR file format utilities, for when PHP phars you up
swop/github-webhook                  v2.0               Library which deals with incoming GitHub web hooks requests (signature validation & payload parsing)
symfony/asset                        v3.4.17            Symfony Asset Component
symfony/browser-kit                  v3.4.17            Symfony BrowserKit Component
symfony/cache                        v3.4.17            Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader                 v3.4.17            Symfony ClassLoader Component
symfony/config                       v3.4.17            Symfony Config Component
symfony/console                      v4.1.7             Symfony Console Component
symfony/debug                        v4.1.7             Symfony Debug Component
symfony/dependency-injection         v3.4.17            Symfony DependencyInjection Component
symfony/dom-crawler                  v3.4.17            Symfony DomCrawler Component
symfony/event-dispatcher             v3.4.17            Symfony EventDispatcher Component
symfony/filesystem                   v3.4.17            Symfony Filesystem Component
symfony/finder                       v4.1.7             Symfony Finder Component
symfony/form                         v3.4.17            Symfony Form Component
symfony/framework-bundle             v3.4.17            Symfony FrameworkBundle
symfony/http-foundation              v3.4.17            Symfony HttpFoundation Component
symfony/http-kernel                  v3.4.17            Symfony HttpKernel Component
symfony/inflector                    v3.4.17            Symfony Inflector Component
symfony/intl                         v3.4.17            A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                         v3.4.17            Symfony Lock Component
symfony/options-resolver             v3.4.17            Symfony OptionsResolver Component
symfony/polyfill-apcu                v1.9.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype               v1.9.0             Symfony polyfill for ctype functions
symfony/polyfill-intl-icu            v1.9.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.10.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.9.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.9.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72               v1.9.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util                v1.9.0             Symfony utilities for portability of PHP codes
symfony/process                      v3.4.17            Symfony Process Component
symfony/property-access              v3.4.17            Symfony PropertyAccess Component
symfony/psr-http-message-bridge      v1.1.0             PSR HTTP message bridge
symfony/routing                      v3.4.17            Symfony Routing Component
symfony/security                     v3.4.17            Symfony Security Component
symfony/security-bundle              v3.4.17            Symfony SecurityBundle
symfony/stopwatch                    v3.4.17            Symfony Stopwatch Component
symfony/templating                   v3.4.17            Symfony Templating Component
symfony/translation                  v3.4.17            Symfony Translation Component
symfony/twig-bridge                  v3.4.17            Symfony Twig Bridge
symfony/twig-bundle                  v3.4.17            Symfony TwigBundle
symfony/validator                    v3.4.17            Symfony Validator Component
symfony/yaml                         v3.4.17            Symfony Yaml Component
theseer/tokenizer                    1.1.0              A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                            v2.5.0             Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.3.0              Assertions to validate method input/output with nice error messages.
zendframework/zend-diactoros         1.7.2              PSR HTTP Message implementations

**Comment by ramunasd** [comment]
Seem fine to me, a little bit outdated but ok.
Can You clear the cache and reproduce that issue?
If yse, then please post steps to reproduce.

**Comment by ramunasd** [comment]
cannot reproduce and no feedback in last 2 weeks
