### ISSUE TITLE
Please add extenions needed to composer.json for transparency

### ISSUE THREAD

**Issue by philipp-heyse** [ludofleury/satisfy#92]
If you don't have the xml extension installed, satisfy installs just fine and even the overview page is working just fine. things break once you go to the config management page.

Its not a critical bug or anything, but it would be nice to document this dependency.
https://getcomposer.org/doc/01-basic-usage.md#platform-packages

Usecase:
Tried building our own docker image and wanted to keep it as slim as possible

Thanks for your work, appreciate it!

**Comment by ramunasd** [comment]
HI, thanks for reporting. I will check why xml extension is required there.
