### ISSUE TITLE
Composer.json doesn't force symfony 3

### ISSUE THREAD

**Issue by N1ghteyes** [ludofleury/satisfy#95]
As it appears that Satisfy doesn't yet support symfony 4, can i suggest that the composer json is amended to prevent symfony 4 being installed by default when composer install is run?

Currently i can't use the UI as my repo server has installed symfony 4 and its erroring out. I have been unable to roll back to symfony 3 (cleanly at least)

Any suggestions for a work around in the mean time?

**Comment by ramunasd** [comment]
Hi @N1ghteyes , thanks for reporting. For now You can use composer.lock file from latest master branch and then just run `composer install`. Everything should be ok.
