### ISSUE TITLE
Webhook timeout

### ISSUE THREAD

**Issue by thorro** [ludofleury/satisfy#98]
It looks like satisfy/webhook tries to synchonously process the request, and GitHub's timeout is quite low, so GH often fails (red triangle), while request is still running on server.

I propose the hook call should be processed asynchronously and 200 returned immediately to GitHub.

**Comment by ramunasd** [comment]
Hi @thorro, thats true, webhook can take a long time to finish the job. It would be nice to have some sort of task manager, but thats additional dependency and complexity. Also, You would not notice any errors from github side, if they occur for some reason.
I will try to send webhook response after validation and before actual processing.

**Comment by ramunasd** [comment]
Hi @thorro , can You test latest master branch. Now github webhooks returns response before actual build and it must take less than second to validate request.

**Comment by ramunasd** [comment]
3 weeks wo response, closing this as fixed.

**Comment by thorro** [comment]
Sorry for no reply, got around to testing it just now. It looks better now, no timeout. Thanks.
